class_name SpectrumReport
extends RefCounted

## Markdown for a [SpectrumHarness] run: the committed `snapshot.md`, and the
## text pasted onto #705. Formatting only — every number is decided in the
## harness.


static func format(result: Dictionary) -> String:
	var params: Dictionary = result["params"]
	var lines: Array[String] = []
	lines.append("# Cyclone curl spectrum (#705)")
	lines.append("")
	lines.append("Generated by `mise run curl-spectrum` — %d-node maps, %d seeds, %d targets per map, %d waves."
			% [params["node_count"], params["seeds"], params["targets"], SpectrumHarness.WAVES])
	lines.append("")
	lines.append("**Informative, never binding.** Same standing as `tools/balance/` —")
	lines.append("these numbers recommend; pinning a coefficient is an owner call.")
	lines.append("")
	lines.append(_calibration_table(result["calibration"]))
	lines.append(_map_table(result["map_rho"]))
	lines.append(_territory_table(result["territory_rho"]))
	lines.append(_wave_table(result["waves"]))
	lines.append(_cast_table(result["casts"]))
	return "\n".join(lines)


static func write_snapshot(result: Dictionary) -> void:
	var file := FileAccess.open(SpectrumHarness.SNAPSHOT_PATH, FileAccess.WRITE)
	if file == null:
		push_warning("SpectrumReport: cannot write %s" % SpectrumHarness.SNAPSHOT_PATH)
		return
	file.store_string(format(result) + "\n")
	file.close()


static func _set_names() -> Array:
	return SpectrumHarness.COEFFICIENT_SETS.keys()


static func _header(first: String) -> Array[String]:
	var names := _set_names()
	var head := "| %s | %s |" % [first, " | ".join(names)]
	var rule := "|---" .repeat(names.size() + 1) + "|"
	return [head, rule]


static func _calibration_table(rows: Array) -> String:
	var lines: Array[String] = []
	lines.append("## A — idealised terrain (calibration)")
	lines.append("")
	lines.append("Reproduces #703's table. If a row here moves, the operator broke —")
	lines.append("`test/unit/spell/test_curl_spectrum.gd` pins it.")
	lines.append("")
	lines.append_array(_header("terrain"))
	for row in rows:
		var cells: Array[String] = []
		for name in _set_names():
			cells.append("%.3f" % float(row["rho"][name]))
		lines.append("| `%s` | %s |" % [row["label"], " | ".join(cells)])
	lines.append("")
	return "\n".join(lines)


static func _map_table(rows: Array) -> String:
	var lines: Array[String] = []
	lines.append("## B — whole-map ρ vs connectivity (a CEILING, not a reading)")
	lines.append("")
	lines.append("A dominant eigenvalue localises onto the densest patch anywhere on the")
	lines.append("map, so this says *somewhere here, a storm could sustain* — never *a cast")
	lines.append("does*. `deg` is the mean graph degree, the honest density number.")
	lines.append("")
	var names := _set_names()
	lines.append("| connectivity | deg | %s |" % " | ".join(names))
	lines.append("|---|---" + "|---".repeat(names.size()) + "|")
	for row in rows:
		var cells: Array[String] = []
		for name in names:
			cells.append("%.3f" % float(row["rho"][name]))
		lines.append("| %.2f | %.2f | %s |"
				% [row["connectivity"], row["degree"], " | ".join(cells)])
	lines.append("")
	return "\n".join(lines)


static func _territory_table(rows: Array) -> String:
	var lines: Array[String] = []
	lines.append("## C — ρ of the territory a cast walks")
	lines.append("")
	lines.append("Cyclone's `OwnerFilter` is Hostile-only, so a cast never sees the whole")
	lines.append("map — it walks one holding's induced subgraph, modelled here as a")
	lines.append("breadth-first ball around the target. Each cell is mean ρ, with the share")
	lines.append("of sampled territories at ρ ≥ 1 (self-sustaining) in brackets.")
	lines.append("")
	for size in SpectrumHarness.BALL_SIZES:
		lines.append("**%d-node territory**" % size)
		lines.append("")
		lines.append_array(_header("connectivity"))
		for row in rows:
			var cells: Array[String] = []
			for name in _set_names():
				var key := "%d|%s" % [size, name]
				cells.append("%.3f (%d%%)" % [
					float(row["rho"][key]), int(round(100.0 * float(row["sustaining"][key])))])
			lines.append("| %.2f | %s |" % [row["connectivity"], " | ".join(cells)])
		lines.append("")
	return "\n".join(lines)


static func _wave_table(rows: Array) -> String:
	var lines: Array[String] = []
	lines.append("## D — total damage of one cast (`max_hops = 8`)")
	lines.append("")
	lines.append("What a cast IS: eight waves, seeded on a legal target (graph degree ≥ 4,")
	lines.append("Cyclone's `min_degree`) with the caster on a neighbour, averaged over every")
	lines.append("arrival edge. Multiples of the seed impact — 1.00 would be *the seed and")
	lines.append("nothing else*.")
	lines.append("")
	var names := _set_names()
	lines.append("Each cell is `territory / whole map`: the same eight waves confined to a")
	lines.append("%d-node holding — the ground `OwnerFilter` (Hostile-only) actually lets a"
			% SpectrumHarness.TERRITORY_DOMAIN)
	lines.append("cast walk — and then over an all-hostile map, which is the ceiling. `Δ8` is")
	lines.append("the whole map's last-wave growth over the wave before it.")
	lines.append("")
	lines.append("| connectivity | %s |" % " | ".join(names))
	lines.append("|---" .repeat(names.size() + 1) + "|")
	for row in rows:
		var cells: Array[String] = []
		for name in names:
			cells.append("%.2f× / %.2f× (Δ8 %.2f)" % [
				float(row["total_ball"][name]),
				float(row["total"][name]),
				float(row["last_growth"][name])])
		lines.append("| %.2f | %s |" % [row["connectivity"], " | ".join(cells)])
	lines.append("")
	lines.append("Per-wave damage for the shipped coefficients (`%s`):" % SpectrumHarness.SHIPPED_LABEL)
	lines.append("")
	lines.append("| connectivity | " + " | ".join(_wave_labels()) + " |")
	lines.append("|---".repeat(SpectrumHarness.WAVES + 1) + "|")
	for row in rows:
		var profile: PackedFloat64Array = row["profile"][SpectrumHarness.SHIPPED_LABEL]
		var cells: Array[String] = []
		for value in profile:
			cells.append("%.2f" % value)
		lines.append("| %.2f | %s |" % [row["connectivity"], " | ".join(cells)])
	lines.append("")
	return "\n".join(lines)


static func _wave_labels() -> Array[String]:
	var out: Array[String] = []
	for w in SpectrumHarness.WAVES:
		out.append("w%d" % (w + 1))
	return out


static func _cast_table(rows: Array) -> String:
	var lines: Array[String] = []
	lines.append("## E — real casts: what the linear model cannot see")
	lines.append("")
	lines.append("`SpellResolver` on the shipped `cyclone.tres` over the same terrain, with")
	lines.append("`closing_gain` moved and the cycle crit stripped (it multiplies what a hop")
	lines.append("LANDS, not what it forwards). Totals are multiples of the seed impact, so")
	lines.append("they read against table D's column for the shipped coefficients. The")
	lines.append("defender's nodes are given 1e7 HP: a kill would truncate the walk and")
	lines.append("confound the walk's growth with the map's HP roll.")
	lines.append("")
	var gains := SpectrumHarness.CLOSING_GAINS
	var gain_labels: Array[String] = []
	for gain in gains:
		gain_labels.append("gain %.2f" % gain)
	lines.append("| connectivity | linear model | %s |" % " | ".join(gain_labels))
	lines.append("|---".repeat(gains.size() + 2) + "|")
	for row in rows:
		var cells: Array[String] = []
		for gain in gains:
			cells.append("%.2f×" % float(row["cast"][gain]))
		lines.append("| %.2f | %.2f× | %s |"
				% [row["connectivity"], float(row["linear"]), " | ".join(cells)])
	lines.append("")
	lines.append("Wave by wave, shipped coefficients and shipped `closing_gain` — the cast")
	lines.append("against the operator's prediction for the same seed, same target, same map:")
	lines.append("")
	lines.append("| connectivity | source | " + " | ".join(_wave_labels()) + " |")
	lines.append("|---".repeat(SpectrumHarness.WAVES + 2) + "|")
	for row in rows:
		lines.append("| %.2f | linear | %s |"
				% [row["connectivity"], _profile_cells(row["linear_profile"])])
		lines.append("| | cast | %s |" % _profile_cells(row["cast_profile"]))
	lines.append("")
	return "\n".join(lines)


static func _profile_cells(profile: PackedFloat64Array) -> String:
	var cells: Array[String] = []
	for w in SpectrumHarness.WAVES:
		cells.append("%.2f" % (profile[w] if w < profile.size() else 0.0))
	return " | ".join(cells)
